services:

  db:
    ports:
      - "1433:1433"
    environment:
      MSSQL_PID: Developer

  backend:
    build:
      target: build
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      NUGET_PACKAGES: /nuget
    volumes:
      - ../../own-delivery-backend/src:/src
      - ../volumes/nuget:/nuget
      - ../../own-delivery-backend/src/OwnDeliveryApiP33/obj:/src/OwnDeliveryApiP33/obj
      - ../../own-delivery-backend/src/OwnDeliveryApiP33/bin:/src/OwnDeliveryApiP33/bin
    command: >
      sh -c "
        dotnet restore OwnDeliveryApiP33/OwnDeliveryApiP33.csproj &&
        dotnet ef database update --project OwnDeliveryApiP33/OwnDeliveryApiP33.csproj &&
        dotnet watch run --project OwnDeliveryApiP33/OwnDeliveryApiP33.csproj --no-launch-profile -- --urls http://+:8080
      "

  design:
    build:
      target: dev
    command: npm run storybook
    volumes:
      - ../../own-delivery-design:/app:ro
      - /app/node_modules

  nginx:
    profiles:
      - with-nginx
